//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Inventory_huan.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMS_Inventory_huan.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chinese 的當地語系化字串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 chokobo 的當地語系化字串。
        /// </summary>
        public static string chokobo {
            get {
                return ResourceManager.GetString("chokobo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompanyCode 的當地語系化字串。
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateDate 的當地語系化字串。
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Details 的當地語系化字串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EmployeeID 的當地語系化字串。
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 InventoryManagementSupplier 的當地語系化字串。
        /// </summary>
        public static string InventoryManagementSupplier {
            get {
                return ResourceManager.GetString("InventoryManagementSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Japanese 的當地語系化字串。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NoStock 的當地語系化字串。
        /// </summary>
        public static string NoStock {
            get {
                return ResourceManager.GetString("NoStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order 的當地語系化字串。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PartNumber 的當地語系化字串。
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PurchaseOrderID 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrderID {
            get {
                return ResourceManager.GetString("PurchaseOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PurchaseOrderStatus  的當地語系化字串。
        /// </summary>
        public static string PurchaseOrderStatus {
            get {
                return ResourceManager.GetString("PurchaseOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QtyPerUnit 的當地語系化字串。
        /// </summary>
        public static string QtyPerUnit {
            get {
                return ResourceManager.GetString("QtyPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ReceiptAddress 的當地語系化字串。
        /// </summary>
        public static string ReceiptAddress {
            get {
                return ResourceManager.GetString("ReceiptAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ReceiverMobile 的當地語系化字串。
        /// </summary>
        public static string ReceiverMobile {
            get {
                return ResourceManager.GetString("ReceiverMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ReceiverName 的當地語系化字串。
        /// </summary>
        public static string ReceiverName {
            get {
                return ResourceManager.GetString("ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ReceiverTel 的當地語系化字串。
        /// </summary>
        public static string ReceiverTel {
            get {
                return ResourceManager.GetString("ReceiverTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ship 的當地語系化字串。
        /// </summary>
        public static string Ship {
            get {
                return ResourceManager.GetString("Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ShipCheck 的當地語系化字串。
        /// </summary>
        public static string ShipCheck {
            get {
                return ResourceManager.GetString("ShipCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ShipDate 的當地語系化字串。
        /// </summary>
        public static string ShipDate {
            get {
                return ResourceManager.GetString("ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ShipmentAmount 的當地語系化字串。
        /// </summary>
        public static string ShipmentAmount {
            get {
                return ResourceManager.GetString("ShipmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ShipNotice 的當地語系化字串。
        /// </summary>
        public static string ShipNotice {
            get {
                return ResourceManager.GetString("ShipNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ShipSucceeded 的當地語系化字串。
        /// </summary>
        public static string ShipSucceeded {
            get {
                return ResourceManager.GetString("ShipSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SignStatus 的當地語系化字串。
        /// </summary>
        public static string SignStatus {
            get {
                return ResourceManager.GetString("SignStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SourceListID 的當地語系化字串。
        /// </summary>
        public static string SourceListID {
            get {
                return ResourceManager.GetString("SourceListID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stock 的當地語系化字串。
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StocksIsNotEnough 的當地語系化字串。
        /// </summary>
        public static string StocksIsNotEnough {
            get {
                return ResourceManager.GetString("StocksIsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Supplier 的當地語系化字串。
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SupplierAccountID 的當地語系化字串。
        /// </summary>
        public static string SupplierAccountID {
            get {
                return ResourceManager.GetString("SupplierAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UnitPrice  的當地語系化字串。
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UnitsInStock 的當地語系化字串。
        /// </summary>
        public static string UnitsInStock {
            get {
                return ResourceManager.GetString("UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UnitsOnOrder  的當地語系化字串。
        /// </summary>
        public static string UnitsOnOrder {
            get {
                return ResourceManager.GetString("UnitsOnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UnshippedOrder 的當地語系化字串。
        /// </summary>
        public static string UnshippedOrder {
            get {
                return ResourceManager.GetString("UnshippedOrder", resourceCulture);
            }
        }
    }
}
